In [1]:
import pandas as pd

In [14]:
import sys
from pathlib import Path

sys.path.append(str(Path("../").resolve()))

In [9]:
df_1 = pd.read_csv("../data/raw/customers_raw_a.csv")
df_2 = pd.read_csv("../data/raw/customers_raw_b.csv")
df_labels = pd.read_csv("../data/labels/column_matches.csv")

In [10]:
display(df_1)
display(df_2)
display(df_labels)

   customer_id    full_name             email signup_date      city
0            1  Anna Müller  anna@example.com  2024-01-10   München
1            2    Max Bauer   max@example.com  2024-02-14  Augsburg
2            3  Lea Schmidt   lea@example.com  2024-03-03    Berlin
3            4   Tom Keller   tom@example.com  2024-03-20   Hamburg

   client_id         name     email_address registration_date  location
0         11  Anna Müller  anna@example.com        2024-01-10   München
1         12    Max Bauer   max@example.com        2024-02-14  Augsburg
2         13  Lea Schmidt   lea@example.com        2024-03-03    Berlin
3         14   Tom Keller   tom@example.com        2024-03-20   Hamburg

       table_a     column_a      table_b           column_b  label
0  customers_a  customer_id  customers_b          client_id      1
1  customers_a    full_name  customers_b               name      1
2  customers_a        email  customers_b      email_address      1
3  customers_a  signup_date  customers_b  registration_date      1
4  customers_a         city  customers_b           location      1
5  customers_a        email  customers_b           location      0
6  customers_a  signup_date  customers_b               name      0
7  customers_a  customer_id  customers_b      email_address      0
8  customers_a         city  customers_b  registration_date      0

In [15]:
from src.dataset import build_pair_dataset

In [23]:
pairs = build_pair_dataset(
    df_a=df_1,
    df_b=df_2,
    labels_df=df_labels,
    table_a_name="customers_a",
    table_b_name="customers_b"
)

In [25]:
display(pairs)
print(pairs.shape)

,text_a,text_b,label
0,"column: customer_id | values: 1, 2, 3, 4","column: client_id | values: 11, 12, 13, 14",1
1,"column: full_name | values: Anna Müller, Max B...","column: name | values: Anna Müller, Max Bauer,...",1
2,"column: email | values: anna@example.com, max@...",column: email_address | values: anna@example.c...,1
3,"column: signup_date | values: 2024-01-10, 2024...",column: registration_date | values: 2024-01-10...,1
4,"column: city | values: München, Augsburg, Berl...","column: location | values: München, Augsburg, ...",1
5,"column: email | values: anna@example.com, max@...","column: location | values: München, Augsburg, ...",0
6,"column: signup_date | values: 2024-01-10, 2024...","column: name | values: Anna Müller, Max Bauer,...",0
7,"column: customer_id | values: 1, 2, 3, 4",column: email_address | values: anna@example.c...,0
8,"column: city | values: München, Augsburg, Berl...",column: registration_date | values: 2024-01-10...,0

(9, 3)